### ISSUE TITLE
Problème Dashboard Codename One: taille de l'application trop lourde pour compte gratuit.

### ISSUE THREAD

**Issue by leadebrincat** [emlyon/codapps#1]
Lorsque j'arrive au Dashboard, j'ai une erreur qui n'est pas répertoriée sur les modules. Je crois qu'on me dit que mon application est trop lourde... Que dois-je faire  ? 
Merci par avance !

<img width="544" alt="erreur" src="https://user-images.githubusercontent.com/36039316/37154349-fff49494-22df-11e8-9c3b-fea02a04df3e.PNG">

**Comment by seinecle** [comment]
Bonjour,
Cette question et sa réponse sont [référencées ici](https://github.com/seinecle/codapps/issues/81).
