### ISSUE TITLE
Problème de code dans module 6

### ISSUE THREAD

**Issue by Dorveaux** [emlyon/codapps#10]
bonjour Monsieur, 
j'ai essayé de modifier les lignesd e code mais je n'arrive toujours pas à faire une preview, pouvez-vous me dire où est le problème ?
![ecran 1](https://user-images.githubusercontent.com/36296420/37862885-cbc868cc-2f54-11e8-898f-ec9222df1cab.png)
![ecran 2](https://user-images.githubusercontent.com/36296420/37862887-cf3617ca-2f54-11e8-8597-5595a87df76c.png)
![ecran 1 my application](https://user-images.githubusercontent.com/36296420/37862888-d2955458-2f54-11e8-940b-b1fe34ab1c5e.png)
![ecran 2 my application](https://user-images.githubusercontent.com/36296420/37862890-d6c04902-2f54-11e8-940f-036c3d2e7b60.png)
respectueusement, 
Alix Dorveaux

**Comment by seinecle** [comment]
Bonjour,
je crois que vous avez ajouté du code "à la main" en ligne 11: c'était une bonne idée!
vous avez juste oublié une majuscule à Grid**L**ayout. A la place de:

`import com.codename1.ui.layouts.Gridlayout;`

mettez:

`import com.codename1.ui.layouts.GridLayout;`

**Comment by Dorveaux** [comment]
Bonsoir Monsieur, 
J'ai corrigé ceci mais la preview ne se lance toujours pas ...
Que puis-je faire ?

**Comment by seinecle** [comment]
Postez ici tout le code de votre fichier Form1.java: pas en copie d'écran mais en copiant collant le texte.
Je le regarderai demain matin. Passez en tutoriel à midi ou le soir pour recevoir de l'aide.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
