### ISSUE TITLE
La preview fonctionne mais n'affiche pas les lignes de code

### ISSUE THREAD

**Issue by LouiseWbr** [emlyon/codapps#11]
Bonjour monsieur,

Je pense avoir codé toutes les lignes correctement, mais la preview n'affiche rien d'autre que l'affichage de départ. Pourriez-vous me dire comment y remédier ?
Merci d'avance !

![image](https://user-images.githubusercontent.com/36113672/37865484-66a7cc20-2f7d-11e8-8276-162190198cab.png)

**Comment by seinecle** [comment]
Bonjour,
Voir la réponse ici : https://github.com/seinecle/codapps/issues/25
