### ISSUE TITLE
Problème d'accès vérification finale  Form1

### ISSUE THREAD

**Issue by ghost** [emlyon/codapps#12]
Bonjour,

je suis arrivé à la fin du module 7. 

Je voudrais vérifier mes lignes de code car le compteur de cookies par seconde ne fonctionne pas: 

![capture d ecran 17](https://user-images.githubusercontent.com/35865477/37867303-6bd128fe-2f96-11e8-8d90-e08231336b1a.png)

Or, je n'arrive pas à accéder au lien: 

![capture d ecran 18](https://user-images.githubusercontent.com/35865477/37867307-748425aa-2f96-11e8-91a2-f267277fb424.png)

Savez-vous pourquoi j'ai ce message d'erreur? Pouvez-vous y remédier? (même en ouvrant la leçon en pdf et en format 'source', je n'arrive pas à y accéder).

Merci d'avance.
Olivier T.

**Comment by seinecle** [comment]
Bonsoir,
Merci pour cette notification. C'était en effet une typo dans le nom du fichier. Je viens de rectifier, le lien devrait marcher désormais.

**Comment by ghost** [comment]
Je viens de vérifier. Le lien fonctionne normalement.
Merci.
Olivier T.
