### ISSUE TITLE
Problème affichage de code en module 6

### ISSUE THREAD

**Issue by clarisselam** [emlyon/codapps#13]
Bonjour, je n'arrive pas à visualiser le preview de l'application. Lorsque je clique sur "Run", rien ne se produit, j'ai le message d'erreur suivant:

"Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
Compiling 3 source files to /Users/clarisselam/NetBeansProjects/Clarisse emlyon/build/tmp
/Users/clarisselam/NetBeansProjects/Clarisse emlyon/src/com/lam/clarisse/myapp/ClarisseCookieClicker.java:58: error: cannot find symbol
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
  symbol:   class UnsupportedOperationException
  location: class ClarisseCookieClicker
/Users/clarisselam/NetBeansProjects/Clarisse emlyon/src/com/lam/clarisse/myapp/ClarisseCookieClicker.java:62: error: cannot find symbol
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
  symbol:   class UnsupportedOperationException
  location: class ClarisseCookieClicker
/Users/clarisselam/NetBeansProjects/Clarisse emlyon/src/com/lam/clarisse/myapp/ClarisseCookieClicker.java:66: error: cannot find symbol
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
  symbol:   class UnsupportedOperationException
  location: class ClarisseCookieClicker
/Users/clarisselam/NetBeansProjects/Clarisse emlyon/src/com/lam/clarisse/myapp/MyApplication.java:41: error: cannot find symbol
        mainScreen.show();
  symbol:   method show()
  location: variable mainScreen of type ClarisseCookieClicker
4 errors
/Users/clarisselam/NetBeansProjects/Clarisse emlyon/build.xml:57: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 1 second)"

**Comment by seinecle** [comment]
Bonjour,
Il y a une série d'erreurs. Compte-tenu du peu de temps restant je vous suggère de passer en tutoriel ce lundi. Sinon nous reprendrons ici mais cela sera plus laborieux.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
