### ISSUE TITLE
problème avec les lignes de code du score

### ISSUE THREAD

**Issue by fleurBr** [emlyon/codapps#14]
Bonjour, 

J'ai une erreur sur ces lignes de codes qui sont les mêmes que celles du cours mais netbeans ne me propose pas de solution et je ne sais pas comment le résoudre
![capture d ecran 2018-03-25 a 10 54 31](https://user-images.githubusercontent.com/36731674/37873292-07dd1cde-301a-11e8-9995-24ca918fbd10.png)

Merci
Fleur B

**Comment by seinecle** [comment]
bonjour,
pouvez vous poster ici, sous form de copier-coller de texte, pas de copie d'écran, l'ensemble de votre code dans le fichier Form1.java? Merci.

**Comment by fleurBr** [comment]
```
package io.codapps.BouronFleurCookieClickerApp;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.Resources;

/**
 *
 * @author fleur
 */
public class Form1 extends com.codename1.ui.Form {
    Resources theme = Resources.getGlobalResources();
   float score = 0f;
   

    public Form1(){
        registerAnimated(this);
   
   Parameters myParameters = new Parameters();
   
  Image farmPic = theme.getImage("farm_50x37.png");
  Image clickPic = theme.getImage("click_50x64.png");
  Image cookieCentraPic = theme.getImage("cookie_200x200.png");
  Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
  
      GridLayout gridLayoutThreeByOne;
       gridLayoutThreeByOne = new GridLayout(3, 1);
      this.setLayout(gridLayoutThreeByOne);
      
      this.setScrollable(false);
      
      Container northRegion = new Container();
      BorderLayout borderLayoutNorth = new BorderLayout();
       northRegion.setLayout(borderLayoutNorth);
       
       Container centerRegion = new Container();
       GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
        centerRegion.setLayout(gridLayoutFourByOne);
        centerRegion.setScrollableY(true);
        
        Container southRegion = new Container();
        BorderLayout blSouth = new BorderLayout();
        southRegion.setLayout(blSouth);
        
        this.addComponent(northRegion);
        this.addComponent(centerRegion);
        this.addComponent(southRegion);
        
        ScaleImageButton cookieCentral;
        cookieCentral = new ScaleImageButton();
        cookieCentral.setIcon(cookieCentraPic);
        cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT);
        cookieCentral.getPressedStyle().setBgImage(cookiePressedPic);
        
        Label scoreLabel = new Label();
        scoreLabel.setText("0 cookies");
        scoreLabel.getStyle().setAlignment(Component.CENTER);
        
        Label cookiesPerSecondLabel = new Label();
cookiesPerSecondLabel.setText("0 per second");
cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER);

northRegion.add(BorderLayout.NORTH, scoreLabel);
northRegion.add(BorderLayout.CENTER, cookieCentral);
northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);

MultiButton autoclickButton = new MultiButton("Auto click");
autoclickButton.setIcon(clickPic);
autoclickButton.setTextLine2("\"Get your fingers some rest\"");
autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");

MultiButton grandmaButton = new MultiButton("Grandma");
        Image grandmaPic = null;
grandmaButton.setIcon(grandmaPic);
grandmaButton.setTextLine2("\"Bake cookies with love\"");
grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");

MultiButton farmButton = new MultiButton("Farm");
farmButton.setIcon(farmPic);
farmButton.setTextLine2("\"Harvest cookies every summer!\"");
farmButton.setTextLine3("each farm produces 3 cookies per second");
farmButton.setTextLine4("price: 500 cookies. Owned: 0");

centerRegion.add(autoclickButton);
centerRegion.add(grandmaButton);
        Container Container; /*add*/
        Container = centerRegion.add(farmButton);
        
        centerRegion.add(autoclickButton);
        centerRegion.add(grandmaButton);
        centerRegion.add(farmButton);
        
        cookieCentral.addActionListener(
        (event) -> { 
            score = score + 1;
            scoreLabel.setText(score + "cookies");
            }
        );
autoclickButton.addActionListener(
        (event) -> {
              if (score >= myParameters.autoclickPrice) {
                  myParameters.autoclickOwned = myParameters.autoclickOwned + 1;
                  score = score - myParameters.autoclickPrice;
                  myParameters.autoclickProd = myParameters.autoclickProd *
  myParameters.rateIncreaseProd;
                  myParameters.autoclickPrice = myParameters.autoclickPrice *
  myParameters.rateIncreasePrice;
                  autoclickButton.setTextLine4("price: " + myParameters.autoclickPrice +
  " cookies. Owned: " + myParameters.autoclickOwned + ".");
                  scoreLabel.setText(score + " cookies");
} }
);

grandmaButton.addActionListener(
(event) -> {
              if (score >= myParameters.grandmaPrice) {
                  myParameters.grandmaOwned = myParameters.grandmaOwned + 1;
                  score = score - myParameters.grandmaPrice;
                  myParameters.grandmaProd = myParameters.grandmaProd * myParameters
  .rateIncreaseProd;
                  myParameters.grandmaPrice = myParameters.grandmaPrice * myParameters
  .rateIncreasePrice;
                  grandmaButton.setTextLine4("price: " + myParameters.grandmaPrice + "
  cookies. Owned: " + myParameters.grandmaOwned + ".");
                  scoreLabel.setText(score + " cookies");
} }
);

farmButton.addActionListener(
          (event) -> {
              if (score >= myParameters.farmPrice) {
                  myParameters.farmOwned = myParameters.farmOwned + 1;
                  score = score - myParameters.farmPrice;
                  myParameters.farmProd = myParameters.farmProd * myParameters
  .rateIncreaseProd;
                  myParameters.farmPrice = myParameters.farmPrice * myParameters
  .rateIncreasePrice;
                  farmButton.setTextLine4("price: " + myParameters.farmPrice + "
  cookies. Owned: " + myParameters.farmOwned + ".");
                  scoreLabel.setText(score + " cookies");
                  } }
);

//a placer quelque part ??

@Override
public boolean animate() {
   computeScore();   // write anything you want here
return true;
       }
 
long lastTimeScoreWasComputed;
private void computeScore() {
long currentTimeInSeconds = System.currentTimeMillis() / 1000;
long lastTimeScoreWasComputedInSeconds = lastTimeScoreWasComputed / 1000;
if (currentTimeInSeconds != lastTimeScoreWasComputedInSeconds) {
score = score + myParameters.grandmaOwned * myParameters.grandmaProd +
myParameters.farmOwned * myParameters.farmProd;
scoreLabel.setText(score + " cookies");
lastTimeScoreWasComputed = System.currentTimeMillis();
} }

    

}

```

**Comment by seinecle** [comment]
- il manque une accolade fermante `}` avant votre ligne qui dit "//a placer quelque part ??"
- sinon votre code ne déclenche pas d'erreur, sauf à la ligne:

`scoreLabel.setText(score + " cookies");`

car [comme expliqué ici](https://github.com/seinecle/codapps/issues/96), votre variable `scoreLabel` doit être déclarée en tête de classe.

**Comment by fleurBr** [comment]
package io.codapps.BouronFleurCookieClickerApp;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.Resources;

/**
 *
 * @author fleur
 */
public class Form1 extends com.codename1.ui.Form {
    Resources theme = Resources.getGlobalResources();
   float score = 0f;
   

    public Form1(){
        registerAnimated(this);
   
   Parameters myParameters = new Parameters();
   
  Image farmPic = theme.getImage("farm_50x37.png");
  Image clickPic = theme.getImage("click_50x64.png");
  Image cookieCentraPic = theme.getImage("cookie_200x200.png");
  Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
  Label scoreLabel = new Label();
Label cookiesPerSecondLabel = new Label();
MultiButton grandmaButton = new MultiButton("Grandma");

      GridLayout gridLayoutThreeByOne;
       gridLayoutThreeByOne = new GridLayout(3, 1);
      this.setLayout(gridLayoutThreeByOne);
      
      this.setScrollable(false);
      
      Container northRegion = new Container();
      BorderLayout borderLayoutNorth = new BorderLayout();
       northRegion.setLayout(borderLayoutNorth);
       
       Container centerRegion = new Container();
       GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
        centerRegion.setLayout(gridLayoutFourByOne);
        centerRegion.setScrollableY(true);
        
        Container southRegion = new Container();
        BorderLayout blSouth = new BorderLayout();
        southRegion.setLayout(blSouth);
        
        this.addComponent(northRegion);
        this.addComponent(centerRegion);
        this.addComponent(southRegion);
        
        ScaleImageButton cookieCentral;
        cookieCentral = new ScaleImageButton();
        cookieCentral.setIcon(cookieCentraPic);
        cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT);
        cookieCentral.getPressedStyle().setBgImage(cookiePressedPic);
        
        
        scoreLabel.setText("0 cookies");
        scoreLabel.getStyle().setAlignment(Component.CENTER);
        

cookiesPerSecondLabel.setText("0 per second");
cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER);

northRegion.add(BorderLayout.NORTH, scoreLabel);
northRegion.add(BorderLayout.CENTER, cookieCentral);
northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);

MultiButton autoclickButton = new MultiButton("Auto click");
autoclickButton.setIcon(clickPic);
autoclickButton.setTextLine2("\"Get your fingers some rest\"");
autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");


        Image grandmaPic = null;
grandmaButton.setIcon(grandmaPic);
grandmaButton.setTextLine2("\"Bake cookies with love\"");
grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");

MultiButton farmButton = new MultiButton("Farm");
farmButton.setIcon(farmPic);
farmButton.setTextLine2("\"Harvest cookies every summer!\"");
farmButton.setTextLine3("each farm produces 3 cookies per second");
farmButton.setTextLine4("price: 500 cookies. Owned: 0");

centerRegion.add(autoclickButton);
centerRegion.add(grandmaButton);
        Container Container; /*add*/
        Container = centerRegion.add(farmButton);
        
        centerRegion.add(autoclickButton);
        centerRegion.add(grandmaButton);
        centerRegion.add(farmButton);
        
        cookieCentral.addActionListener(
        (event) -> { 
            score = score + 1;
            scoreLabel.setText(score + "cookies");
            }
        );
autoclickButton.addActionListener(
        (event) -> {
              if (score >= myParameters.autoclickPrice) {
                  myParameters.autoclickOwned = myParameters.autoclickOwned + 1;
                  score = score - myParameters.autoclickPrice;
                  myParameters.autoclickProd = myParameters.autoclickProd *
  myParameters.rateIncreaseProd;
                  myParameters.autoclickPrice = myParameters.autoclickPrice *
  myParameters.rateIncreasePrice;
                  autoclickButton.setTextLine4("price: " + myParameters.autoclickPrice +
  " cookies. Owned: " + myParameters.autoclickOwned + ".");
                  scoreLabel.setText(score + " cookies");
} }
);

grandmaButton.addActionListener(
(event) -> {
              if (score >= myParameters.grandmaPrice) {
                  myParameters.grandmaOwned = myParameters.grandmaOwned + 1;
                  score = score - myParameters.grandmaPrice;
                  myParameters.grandmaProd = myParameters.grandmaProd * myParameters
  .rateIncreaseProd;
                  myParameters.grandmaPrice = myParameters.grandmaPrice * myParameters
  .rateIncreasePrice;
                  grandmaButton.setTextLine4("price: " + myParameters.grandmaPrice + "
  cookies. Owned: " + myParameters.grandmaOwned + ".");
                  scoreLabel.setText(score + " cookies");
} }
);

farmButton.addActionListener(
          (event) -> {
              if (score >= myParameters.farmPrice) {
                  myParameters.farmOwned = myParameters.farmOwned + 1;
                  score = score - myParameters.farmPrice;
                  myParameters.farmProd = myParameters.farmProd * myParameters
  .rateIncreaseProd;
                  myParameters.farmPrice = myParameters.farmPrice * myParameters
  .rateIncreasePrice;
                  farmButton.setTextLine4("price: " + myParameters.farmPrice + "
  cookies. Owned: " + myParameters.farmOwned + ".");
                  scoreLabel.setText(score + " cookies");
                  } }
);
}
//a placer quelque part ??

@Override
public boolean animate() {
   computeScore();   // write anything you want here
return true;
       }
 
long lastTimeScoreWasComputed;
private void computeScore() {
long currentTimeInSeconds = System.currentTimeMillis() / 1000;
long lastTimeScoreWasComputedInSeconds = lastTimeScoreWasComputed / 1000;
if (currentTimeInSeconds != lastTimeScoreWasComputedInSeconds) {
score = score + myParameters.grandmaOwned * myParameters.grandmaProd +
myParameters.farmOwned * myParameters.farmProd;
scoreLabel.setText(score + " cookies");
lastTimeScoreWasComputed = System.currentTimeMillis();
} }

    

}
    
  j'ai un problème qui persiste  sur ces lignes la : 
      grandmaButton.setTextLine4("price: " + myParameters.grandmaPrice + "
  cookies. Owned: " + myParameters.grandmaOwned + ".");
                  scoreLabel.setText(score + " cookies");
} }
);

est ce aussi u problème d'annonce de variable au départ?

merci

**Comment by seinecle** [comment]
Non je ne crois pas... pouvez-vous passer dans 30 minutes au tutoriel? Sinon, poster ici le message d'erreur?

**Comment by fleurBr** [comment]
quand je clique sur l'erreur cela m'indique deux options (qui ne résolvent finalement pas l'erreur après) - "use anonymous inner class" ou "Assign return value to new variable"

**Comment by fleurBr** [comment]
problème résolu merci
