### ISSUE TITLE
méthode animate 

### ISSUE THREAD

**Issue by fleurBr** [emlyon/codapps#15]
Bonjour, 

Je ne comprends pas ou doit on placer ces lignes de codes : 

@Override
public boolean animate() {
   computeScore();   // write anything you want here
return true;
       }
 
long lastTimeScoreWasComputed;
private void computeScore() {
long currentTimeInSeconds = System.currentTimeMillis() / 1000;
long lastTimeScoreWasComputedInSeconds = lastTimeScoreWasComputed / 1000;
if (currentTimeInSeconds != lastTimeScoreWasComputedInSeconds) {
score = score + myParameters.grandmaOwned * myParameters.grandmaProd +
myParameters.farmOwned * myParameters.farmProd;
scoreLabel.setText(score + " cookies");
lastTimeScoreWasComputed = System.currentTimeMillis();
} }

merci
Merci
Fleur B

**Comment by seinecle** [comment]
Vous devez les placer dans la classe `Form1` , c'est à dire dans le fichier `Form1.java`. Où dans ce fichier? Où vous le souhaitez, mais par convention:
- les variables s'écrivent "en tête" (en haut) de la classe, juste après le `public class Form1 extends ... {`
- les méthodes s'écrivent dans n'importe quel ordre, mais on les écrit traditionnellement **après** la méthode "constructeur" (celle qui porte le même nom que la classe, et qui s'éxecute quand la classe est instantiée).
- n'oubliez pas, après la dernière méthode écrite, de bien mettre l'accolade fermante `}` de la classe ...

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
