### ISSUE TITLE
Final Version of the code in the file Form1

### ISSUE THREAD

**Issue by ymeissonnier** [emlyon/codapps#16]
At the end of module 7, we should be able to access the full code of Form1, to check whether we have entered the right code or not.
The problem is that the page doesn't work as I reach a "404 File not found" screen.

Could you fix that please ? Because my app doesn't work and I don't understand why.

Yours faithfully,

Yaëlis Meissonnier

**Comment by seinecle** [comment]
This has been fixed now. Thanks for the notification.
