### ISSUE TITLE
problème de crochet sur la dernière ligne de code

### ISSUE THREAD

**Issue by OihanaMilloxItoiz** [emlyon/codapps#17]
Bonjour, il me semble avoir bien fait les modules 6 et 7. Pourtant, quand je cherche à lancer l'application il semblerait que le dernier crochet bloque le lancement (signe "attention" en face du crochet).
Voici un copier-coller de mon codage : 

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emlyon.myfirstapp;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.Resources;

public class Form1 extends com.codename1.ui.Form {

  Resources theme = Resources.getGlobalResources();
  float score = 0f;
  Parameters myParameters = new Parameters();
  
  public Form1() {
      Image grandmaPic = theme.getImage("grandma_50x50.png");
      Image farmPic = theme.getImage("farm_50x37.png");
      Image clickPic = theme.getImage("click_50x64.png");
      Image cookieCentraPic = theme.getImage("cookie_200x200.png");
      Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
      
      GridLayout gridLayoutThreeByOne = new GridLayout(3, 1);
      this.setLayout(gridLayoutThreeByOne);
      
      this.setScrollable(false);
      
      Container northRegion = new Container();
      
      BorderLayout borderLayoutNorth = new BorderLayout();
      northRegion.setLayout(borderLayoutNorth);
      
      Container centerRegion = new Container();
      
      GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
      centerRegion.setLayout(gridLayoutFourByOne);
      
      centerRegion.setScrollableY(true);
      
      Container southRegion = new Container();
      BorderLayout blSouth = new BorderLayout();
      southRegion.setLayout(blSouth);
      
      this.addComponent(northRegion);
      this.addComponent(centerRegion);
      this.addComponent(southRegion);
      
      ScaleImageButton cookieCentral = new ScaleImageButton();
      cookieCentral.setIcon(cookieCentraPic);
      cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT);
      cookieCentral.getPressedStyle().setBgImage(cookiePressedPic);
      
      Label scoreLabel = new Label();
      scoreLabel.setText("0 cookies");
      scoreLabel.getStyle().setAlignment(Component.CENTER);
      
      Label cookiesPerSecondLabel = new Label();
      cookiesPerSecondLabel.setText("0 per second");
      cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER);
      
      northRegion.add(BorderLayout.NORTH, scoreLabel);
      northRegion.add(BorderLayout.CENTER, cookieCentral);
      northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);
      
      MultiButton autoclickButton = new MultiButton("Auto click");
      autoclickButton.setIcon(clickPic);
      autoclickButton.setTextLine2("\"Get your fingers some rest\"");
      autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
      autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");
      
      MultiButton grandmaButton = new MultiButton("Grandma");
      grandmaButton.setIcon(grandmaPic);
      grandmaButton.setTextLine2("\"Bake cookies with love\"");
      grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
      grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");
      
      MultiButton farmButton = new MultiButton("Farm");
      farmButton.setIcon(farmPic);
      farmButton.setTextLine2("\"Harvest cookies every summer!\"");
      farmButton.setTextLine3("each farm produces 3 cookies per second");
      farmButton.setTextLine4("price: 500 cookies. Owned: 0");
      
      centerRegion.add(autoclickButton);
      centerRegion.add(grandmaButton);
      centerRegion.add(farmButton);
      
      cookieCentral.addActionListener(
              (event) -> { 
                  score = score + 1;
                  scoreLabel.setText(score + " cookies");
              }
            );
      
      autoclickButton.addActionListener(
              (ActionEvent event) -> {
                  if (score >= myParameters.autoclickPrice) {
                      myParameters.autoclickOwned = myParameters.autoclickOwned + 1;
                      score = score - myParameters.autoclickPrice;
                      myParameters.autoclickProd = myParameters.autoclickProd * myParameters.rateIncreaseProd;
                      myParameters.autoclickPrice = myParameters.autoclickPrice * myParameters.rateIncreasePrice;
                      autoclickButton.setTextLine4("price: " + myParameters.autoclickPrice + " cookies. Owned: " + myParameters.autoclickOwned + ".");
                      scoreLabel.setText(score + " cookies");
                  }
              }      
              
        );
      
      grandmaButton.addActionListener(
              (ActionEvent event) -> {
                   if (score >= myParameters.grandmaPrice) {
                       myParameters.grandmaOwned = myParameters.grandmaOwned + 1;
                       score = score - myParameters.grandmaPrice;
                       myParameters.grandmaProd = myParameters.grandmaProd * myParameters.rateIncreaseProd;
                       myParameters.grandmaPrice = myParameters.grandmaPrice * myParameters.rateIncreasePrice;
                       grandmaButton.setTextLine4("price: " + myParameters.grandmaPrice + " cookies. Owned: " + myParameters.grandmaOwned + ".");
                       scoreLabel.setText(score + " cookies");
                       
                   }
              }
              
        ); 
      
      farmButton.addActionListener(
              (event) -> {
                  if (score >= myParameters.farmPrice) {
                      myParameters.farmOwned = myParameters.farmOwned + 1;
                      score = score - myParameters.farmPrice;
                      myParameters.farmProd = myParameters.farmProd * myParameters.rateIncreaseProd;
                      myParameters.farmPrice = myParameters.farmPrice * myParameters.rateIncreasePrice;
                      farmButton.setTextLine4("price: " + myParameters.farmPrice + " cookies. Owned: " + myParameters.farmOwned + ".");
                      scoreLabel.setText(score + " cookies");
                  }
              }
        );      
}

Merci d'avance pour votre aide, 
Oihana Millox Itoiz.

**Comment by seinecle** [comment]
Effectivement il vous manque une accolade fermante `}` à la toute fin pour clore votre classe. Vous en avez déjà un mais ce n'est pas suffisant : celui que vous avez clôt la méthode, il vous en manque donc un autre pour clore la classe.

**Comment by OihanaMilloxItoiz** [comment]
Merci beaucoup.
