### ISSUE TITLE
problème leçon "inner class" make variable final in module 7

### ISSUE THREAD

**Issue by ludivineporot** [emlyon/codapps#18]
Bonsoir,

Mon problème est lié aux lignes de codes qui modifient le score, il ya une erreur (avec -je crois- la variable score qui n'est pas reconnue même si j'ai mis la ligne "   float score = 0f; ") que je ne sais pas comment résoudre. 

Merci de votre aide,

Ludivine Porot
![probleme codapps 2](https://user-images.githubusercontent.com/35995486/37878100-0c4e6a4e-3064-11e8-86fd-8593ef8d2d7c.png)
![probleme codapps](https://user-images.githubusercontent.com/35995486/37878101-0c79f498-3064-11e8-8d41-c2f965240655.png)

**Comment by seinecle** [comment]
Oui un certain nombre d'autres étudiants postent ce problème. Je vois que vous avez clos cette question, l'avez-vous résolue et si oui comment?

**Comment by ludivineporot** [comment]
Bonjour, 

oui j’ai réussi à le résoudre en définissant la variable score avant la ligne « public form 1 » (la leçon nous dit de la nommer après public form 1). Je suis par contre bloquée à la dernière leçon du dernier module, notamment puisque netbeans ne reconnaît pas « my parameters » ou « farmowned » etc. Que faire s’il vous plait ? 

Bien à vous,


Ludivine Porot 

Envoyé depuis mon iPhone en utilisant IBM Verse

Le 25 mars 2018 à 22:42:36, notifications@github.com a écrit :

**Comment by seinecle** [comment]
Bonjour,
Pouvez-vous poster le code (copier-coller le texte, pas une copie d'écran) et le message d'erreur? Faites-le dans une nouvelle issue svp (je ferme celle-ci car votre question précédente est résolue).

**Comment by ludivineporot** [comment]
Bonjour,

J’ai réussi à lancer l’application avec toutes les lignes donc j’ai résolu le bug mais il y a un problème avec le fonctionnement de l’appli. J’ai ouvert une nouvelle issue avec mon code en copier/coller.

Merci d’avance,

Ludivine Porot 

Envoyé depuis mon iPhone en utilisant IBM Verse

Le 29 mars 2018 à 09:53:08, notifications@github.com a écrit :
