### ISSUE TITLE
Module 6: je n'obtiens pas le rendu final du module.

### ISSUE THREAD

**Issue by ghost** [emlyon/codapps#2]
Après avoir vu le rendu intermédiaire du module 6,
je n'obtiens pas le même rendu final alors que j'ai tout recopié correctement.
![code 1](https://user-images.githubusercontent.com/35698106/37471578-6e1f71fc-286a-11e8-8b53-7771c90d5737.PNG)
![code2](https://user-images.githubusercontent.com/35698106/37471579-6e4619ce-286a-11e8-9ffb-8af4e527e948.PNG)
![rendu final module 6](https://user-images.githubusercontent.com/35698106/37471580-6e6eb226-286a-11e8-9615-8079bc5fa47c.PNG)

Est-ce bien cela qu'il faut obtenir à la fin du module 6 ?

**Comment by seinecle** [comment]
Oui:

- n'hésitez pas à passer sur une [skin différente](https://emlyon.github.io/codapps/generated-html/creating-your-first-project-and-previewing-your-app.html#_b_adjusting_the_size_of_the_skin_to_the_screen).
- vous pouvez faire un scroll down avec votre souris dans la zone centrale pour révéler les autres "outils" (grandma et farm).

**Comment by seinecle** [comment]
Bonjour, la dernière réponse à cette issue date de plus de 8 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
