### ISSUE TITLE
probleme "Component is already contained in Container"

### ISSUE THREAD

**Issue by AlexandreMANSOTTE** [emlyon/codapps#20]
Bonjour,

je n'arrive pas à visualiser le prives de l'app. L'app semble se lancer, la fenêtre "simulator" s'ouvre puis disparait aussitôt...

ci joint le message que j'obtient.

<img width="1086" alt="capture d ecran 2018-03-26 a 12 17 06" src="https://user-images.githubusercontent.com/35762030/37900867-c2ef4508-30ef-11e8-972c-4b1906b68778.png">

**Comment by seinecle** [comment]
Il semble qu'à la ligne 102 de votre fichier Form1.java, vous ajoutez un Component qui a déjà été ajouté à une ligne plus haut dans votre code.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
