### ISSUE TITLE
Méthode computeScore et autres variables et méthodes soulignées en rouge

### ISSUE THREAD

**Issue by alicemartos** [emlyon/codapps#21]
Bonjour, j'ai inséré ces lignes mais elles ne semblent pas correctes... 
Pourriez vous m'aider s'il vous plait ?

Merci ! 

Alice Martos

![1](https://user-images.githubusercontent.com/35902566/37933635-15112354-314c-11e8-820e-0a92ec3985a9.png)
![2](https://user-images.githubusercontent.com/35902566/37933636-153c6708-314c-11e8-82b0-d8e08bfa0ecb.png)
![3](https://user-images.githubusercontent.com/35902566/37933637-15641b72-314c-11e8-846e-8f4f3ac41cf9.png)
![4](https://user-images.githubusercontent.com/35902566/37933639-1595c0d2-314c-11e8-9d45-cca5cc617bd1.png)
![5](https://user-images.githubusercontent.com/35902566/37933641-15c0eb40-314c-11e8-8a2f-e0e937953c6f.png)

**Comment by seinecle** [comment]
Bonjour,

C'est le même problème que [dans cette question](https://github.com/seinecle/codapps/issues/115).
Votre méthode `animate()` contient des lignes de code qui font référence à des variables (`lastAnimatedTime`) et des méthodes (`computeScore` par exemple) **que vous n'avez pas encore écrites dans votre code**. Les messages d'erreur disent simplement: quelles sont ces variables et ces méthodes?

Solution: reprendre la leçon dans l'ordre et écrire les lignes de code nécessaires, dans l'ordre.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
