### ISSUE TITLE
Mauvais écran qui s'affiche à la fin.

### ISSUE THREAD

**Issue by LouiseWbr** [emlyon/codapps#23]
Bonjour Monsieur,

J'ai tout recommencé et ai recopié les lignes de code correctement. La preview fonctionne, affiche autre chose, mais toujours pas ce qui est attendu: 
![image](https://user-images.githubusercontent.com/36113672/37975107-dcbff848-31de-11e8-92d4-1543b4285299.png)

Comment faire ?

Merci d'avance,

Louise Weber

**Comment by seinecle** [comment]
Bonjour,
[Voir cette réponse](https://github.com/seinecle/codapps/issues/25).
