### ISSUE TITLE
Problème "grandmaButton" fin module 6

### ISSUE THREAD

**Issue by JessicaBe** [emlyon/codapps#24]
Bonjour, 

Après avoir recopié exactement les mêmes lignes de code, je me retrouve avec un problème au niveau du bouton "grandma". En cliquant sur l'ampoule afin de "corriger", cela me propose de créer une nouvelle variable (voir screen). Lorsque je fais la preview, seule le bouton autoclick s'affiche.

Merci pour votre réponse. 
![image](https://user-images.githubusercontent.com/36131324/37978318-114c3674-31e6-11e8-9b0c-4157c783b7bc.png)

![image](https://user-images.githubusercontent.com/36131324/37978297-086b17dc-31e6-11e8-80f3-c710b796e856.png)

**Comment by seinecle** [comment]
Problème résolu?

**Comment by JessicaBe** [comment]
Bonjour Monsieur,

Oui j’ai trouvé mon erreur. Merci beaucoup.

Jessica Benattar



Le 29 mars 2018 à 10:03:18 AM, notifications@github.com a écrit :
