### ISSUE TITLE
Impossible de lancer la preview

### ISSUE THREAD

**Issue by LisonBel** [emlyon/codapps#26]
Bonjour, j'ai codé entièrement l'appli et je ne peux pas lancer la preview... la fenêtre du simulator s'ouvre et se referme directement, sans rien afficher... je ne comprends pas d'où viens le problème, j'ai vérifié mon code 3 fois... ce message d'erreur s'affiche. 
Merci d'avance 
![capture d ecran 2018-03-28 a 14 51 09](https://user-images.githubusercontent.com/36737637/38030049-d35442be-3297-11e8-965a-5daf742ff469.png)

**Comment by seinecle** [comment]
Le message d'erreur dit qu'il y a un problème à la ligne 26 de votre fichier `MyApplication.java`, pouvez vous copier-coller le texte (pas une copie d'écran) de ce fichier?

**Comment by LisonBel** [comment]
J’ai recommencé un nouveau projet et ça fonctionne, merci de votre réponse.
