### ISSUE TITLE
lien Google play

### ISSUE THREAD

**Issue by hortensedenicolay** [emlyon/codapps#28]
Bonjour Monsieur , je ne trouve pas le lien Google play pour l'installation de l'application sur android , pouvez vous me le donner ?

Merci beaucoup

**Comment by seinecle** [comment]
Bonjour,
il n'y a pas besoin de l'invitation pour installer sur votre propre téléphone Android. [Cela prend 5 minutes et c'est expliqué ici.](https://emlyon.github.io/codapps/generated-html/testing-and-releasing-for-android.html#_b_create_a_developer_account_on_google_s_play_store_25)
