### ISSUE TITLE
Problème premières étapes module 6

### ISSUE THREAD

**Issue by alicemartos** [emlyon/codapps#3]
Bonjour, j'ai bien lu le module 5 et j'ai suivie la première étape du module 6 mais je n'arrive pas à faire apparaitre mon application.

![capture d ecran 2018-03-18 a 19 00 44](https://user-images.githubusercontent.com/35902566/37569247-dd9330ec-2adf-11e8-8573-b88e2cf5ce1b.png)
![capture d ecran 2018-03-18 a 19 01 16](https://user-images.githubusercontent.com/35902566/37569249-e4d3146c-2adf-11e8-968a-fd4a1be84e92.png)
 
Merci d'avance pour votre aide !

**Comment by seinecle** [comment]
Bonjour,

L'accolade fermante en ligne 31 `}` "achève" ou "clos" le code de votre classe. Toutes les lignes qui suivent sont donc considérées comme invalides. Solution:

- enlevez l'accolade fermante de la ligne 31, et mettez-à tout en bas, en ligne 54.

**Comment by seinecle** [comment]
Bonjour, la dernière réponse à cette issue date de 6 jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
