### ISSUE TITLE
Démarrage de l'application

### ISSUE THREAD

**Issue by olenoel** [emlyon/codapps#30]
Bonjour Monsieur, 
Je ne parviens pas à démarrer le preview de l'application. Form1 ne me pose pas de soucis, mais c'est au moment de compléter MyApplication.java pour que la preview démarre Form1, le fichier source MyApplication.java part complètement en cacahouète... Voici un screen. En regardant l'application réalisée au début j'ai remarqué une différence : ici nous parlons de mainscreen et non pus de myform1, peut-être que cela vient de là ? Merci par avance, 
Cordialement, 
Oscar Lenoel
![capture d ecran 2018-03-29 a 15 12 42](https://user-images.githubusercontent.com/37904132/38091531-185231d6-3366-11e8-8d5a-54ed715c2343.png)

**Comment by seinecle** [comment]
Oui effectivement... toutes ces lignes (de 50 à 64 et peut-être plus) doivent être supprimées. Essayez de tout supprimer après la ligne 49, et de rajouter juste une accolade fermante `}` en ligne 49 : ca devrait suffire.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
