### ISSUE TITLE
Blocage aux modules 6 et 7

### ISSUE THREAD

**Issue by nono35v** [emlyon/codapps#4]
Bonjour,

J'ai recopié les lignes de code. Pourtant, je n'arrive pas à lancer l'appli sur le logiciel NetBeans.
J'ai aussi certaines lignes de code avec le signal de la petite lampe que j'arrive parfois à régler et parfois non. De même avec le symbole rouge à droite des captures d'écran.

Pourriez-vous m'expliquer comment remédier à cela ?

![image](https://user-images.githubusercontent.com/35846302/37719025-5d5dc2ba-2d24-11e8-9d11-d13925a2e57a.png)
![image](https://user-images.githubusercontent.com/35846302/37719038-64cf4d84-2d24-11e8-8c77-95db77b9aa5d.png)
![image](https://user-images.githubusercontent.com/35846302/37719044-6bc02a28-2d24-11e8-9622-5a4c5f6c1032.png)

![image](https://user-images.githubusercontent.com/35846302/37719054-7162bdce-2d24-11e8-8077-6cbc359c2397.png)

Merci d'avance

Noureddine

**Comment by seinecle** [comment]
Pouvez copier coller ici, sous forme de texte (pas une copie d'écran) le contenu de votre Form1? Merci

**Comment by nono35v** [comment]
Oui bien sûr : 

package net.clementlevallois.net.cookieclicker.ultimate;

import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.Resources;
import com.cookieclicker.myfirstapp.Parameters;

public class Form1 extends com.codename1.ui.Form {

    Resources theme;


    public Form1() {

        theme = Resources.getGlobalResources();
        float score = 0f;
        Parameters myParameters = new Parameters();
        
        Image grandmaPic = theme.getImage("grandma_50x50.png");
        Image farmPic = theme.getImage("farm_50x37.png");
        Image clickPic = theme.getImage("click_50x64.png");
        Image cookieCentraPic = theme.getImage("cookie_200x200.png");
        Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");

        //we put the Form in a Grid layout: 3 rows, to divide the screen in three equal spaces.
        GridLayout gridLayoutThreeByOne = new GridLayout(3, 1);
        this.setLayout(gridLayoutThreeByOne);

        //we don't want the screen to be scrollable: everything should fit in it.
        this.setScrollable(false);

        //we create a Container that will contain everything in the "North" part of the BorderLayout:
        Container northRegion = new Container();

        //we choose a Border Layout for this container:
        BorderLayout borderLayoutNorth = new BorderLayout();
        northRegion.setLayout(borderLayoutNorth);


        //we create a Container that will contain everything in the "Center" part of the screen:
        Container centerRegion = new Container();

        //we choose a Grid Layout for this container:
        GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
        centerRegion.setLayout(gridLayoutFourByOne);

        //we set this region to be scrollable, because there is too much content to fit
        centerRegion.setScrollableY(true);

        //we create a Container that will contain everything in the "South" part of the BorderLayout:
        Container southRegion = new Container();

        //we choose a Border Layout for this container:
        BorderLayout blSouth = new BorderLayout();
        southRegion.setLayout(blSouth);

        // we add the three containers to the Form, which is in a Gridlayout (three rows)
        // The northRegion will be in the top row because we add it first,
        // The centerRegion will be in the 2nd row because we add it in second
        // The southRegion will be in the 3rd row because we add it last.
        this.addComponent(northRegion);
        this.addComponent(centerRegion);
        this.addComponent(southRegion);
        
        ScaleImageButton cookieCentral = new ScaleImageButton();
        cookieCentral.setIcon(cookieCentraPic);
        cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT); 
        cookieCentral.getPressedStyle().setBgImage(cookiePressedPic);
        
        Label scoreLabel = new Label();
        scoreLabel.setText("0 cookies");
        scoreLabel.getStyle().setAlignment(Component.CENTER);
        
        Label cookiesPerSecondLabel = new Label();
        cookiesPerSecondLabel.setText("0 per second");
        cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER);
        
        northRegion.add(BorderLayout.NORTH, scoreLabel);
        northRegion.add(BorderLayout.CENTER, cookieCentral);
        northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);
        
        MultiButton autoclickButton = new MultiButton("Auto click"); 
        autoclickButton.setIcon(clickPic);
        autoclickButton.setTextLine2("\"Get your fingers some rest\"");
        autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
        autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");
        
        MultiButton grandmaButton = new MultiButton("Grandma");
        grandmaButton.setIcon(grandmaPic); 
        grandmaButton.setTextLine2("\"Bake cookies with love\"");
        grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
        grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");
        
        MultiButton farmButton = new MultiButton("Farm");
        farmButton.setIcon(farmPic);
        farmButton.setTextLine2("\"Harvest cookies every summer!\"");
        farmButton.setTextLine3("each farm produces 3 cookies per second");
        farmButton.setTextLine4("price: 500 cookies. Owned: 0");
        
        centerRegion.add(autoclickButton);
        centerRegion.add(grandmaButton);
        centerRegion.add(farmButton);
        
        centerRegion.add(autoclickButton);
        centerRegion.add(grandmaButton);
        centerRegion.add(farmButton);
        
        cookieCentral.addActionListener( 
                (event) -> { 
                    score = score + 1;
                    scoreLabel.setText(score + " cookies");         
                    }
            );    
        autoclickButton.addActionListener(  
                (event) -> {
                    if (score >= myParameters.autoclickPrice) {
                        myParameters.autoclickOwned = myParameters.autoclickOwned + 1;
                        score = score - myParameters.autoclickPrice;
                        myParameters.autoclickProd = myParameters.autoclickProd *
myParameters.rateIncreaseProd;
                        myParameters.autoclickPrice = myParameters.autoclickPrice *
myParameters.rateIncreasePrice;
                        autoclickButton.setTextLine4("price: " + myParameters.autoclickPrice +
" cookies. Owned: " + myParameters.autoclickOwned + ".");
                        scoreLabel.setText(score + " cookies");
                    }
                }           
        );

        





        


        



    }

}

**Comment by seinecle** [comment]
Le package name en tête est le mien. Que se passe t il lorsque vous mettez le package name correct? (c'est à dire le vôtre, qui est écrit par défaut en haut lorsque vous créez le fichier Form)

**Comment by nono35v** [comment]
Dois je remplacer " package net.clementlevallois.net.cookieclicker.ultimate; " 
par " package net.noureddine.cookieclicker.ultimate;   " ? Car si c'est ça, j'ai essayé et ça ne marche pas, et à vrai dire je ne sais pas quel nom mettre à la place de clementlevallois, dois je mettre Noureddine? je comprends pas trop quand vous dites " que se passe t il lorsque vous mettez le package name correct

**Comment by nono35v** [comment]
package com.cookieclicker.myfirstapp;

import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.Resources;
import com.cookieclicker.myfirstapp.Parameters;

public class Form1 extends com.codename1.ui.Form {

    Resources theme;


    public Form1() {

        theme = Resources.getGlobalResources();
        float score = 0f;
        Parameters myParameters = new Parameters();
        
        Image grandmaPic = theme.getImage("grandma_50x50.png");
        Image farmPic = theme.getImage("farm_50x37.png");
        Image clickPic = theme.getImage("click_50x64.png");
        Image cookieCentraPic = theme.getImage("cookie_200x200.png");
        Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");

        //we put the Form in a Grid layout: 3 rows, to divide the screen in three equal spaces.
        GridLayout gridLayoutThreeByOne = new GridLayout(3, 1);
        this.setLayout(gridLayoutThreeByOne);

        //we don't want the screen to be scrollable: everything should fit in it.
        this.setScrollable(false);

        //we create a Container that will contain everything in the "North" part of the BorderLayout:
        Container northRegion = new Container();

        //we choose a Border Layout for this container:
        BorderLayout borderLayoutNorth = new BorderLayout();
        northRegion.setLayout(borderLayoutNorth);


        //we create a Container that will contain everything in the "Center" part of the screen:
        Container centerRegion = new Container();

        //we choose a Grid Layout for this container:
        GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
        centerRegion.setLayout(gridLayoutFourByOne);

        //we set this region to be scrollable, because there is too much content to fit
        centerRegion.setScrollableY(true);

        //we create a Container that will contain everything in the "South" part of the BorderLayout:
        Container southRegion = new Container();

        //we choose a Border Layout for this container:
        BorderLayout blSouth = new BorderLayout();
        southRegion.setLayout(blSouth);

        // we add the three containers to the Form, which is in a Gridlayout (three rows)
        // The northRegion will be in the top row because we add it first,
        // The centerRegion will be in the 2nd row because we add it in second
        // The southRegion will be in the 3rd row because we add it last.
        this.addComponent(northRegion);
        this.addComponent(centerRegion);
        this.addComponent(southRegion);
        
        ScaleImageButton cookieCentral = new ScaleImageButton();
        cookieCentral.setIcon(cookieCentraPic);
        cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT); 
        cookieCentral.getPressedStyle().setBgImage(cookiePressedPic);
        
        Label scoreLabel = new Label();
        scoreLabel.setText("0 cookies");
        scoreLabel.getStyle().setAlignment(Component.CENTER);
        
        Label cookiesPerSecondLabel = new Label();
        cookiesPerSecondLabel.setText("0 per second");
        cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER);
        
        northRegion.add(BorderLayout.NORTH, scoreLabel);
        northRegion.add(BorderLayout.CENTER, cookieCentral);
        northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);
        
        MultiButton autoclickButton = new MultiButton("Auto click"); 
        autoclickButton.setIcon(clickPic);
        autoclickButton.setTextLine2("\"Get your fingers some rest\"");
        autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
        autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");
        
        MultiButton grandmaButton = new MultiButton("Grandma");
        grandmaButton.setIcon(grandmaPic); 
        grandmaButton.setTextLine2("\"Bake cookies with love\"");
        grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
        grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");
        
        MultiButton farmButton = new MultiButton("Farm");
        farmButton.setIcon(farmPic);
        farmButton.setTextLine2("\"Harvest cookies every summer!\"");
        farmButton.setTextLine3("each farm produces 3 cookies per second");
        farmButton.setTextLine4("price: 500 cookies. Owned: 0");
        
        centerRegion.add(autoclickButton);
        centerRegion.add(grandmaButton);
        centerRegion.add(farmButton);
        
        centerRegion.add(autoclickButton);
        centerRegion.add(grandmaButton);
        centerRegion.add(farmButton);
        
        cookieCentral.addActionListener( 
                (event) -> { 
                    score = score + 1;
                    scoreLabel.setText(score + " cookies");         
                    }
            );    
        autoclickButton.addActionListener(  
                (event) -> {
                    if (score >= myParameters.autoclickPrice) {
                        myParameters.autoclickOwned = myParameters.autoclickOwned + 1;
                        score = score - myParameters.autoclickPrice;
                        myParameters.autoclickProd = myParameters.autoclickProd *
myParameters.rateIncreaseProd;
                        myParameters.autoclickPrice = myParameters.autoclickPrice *
myParameters.rateIncreasePrice;
                        autoclickButton.setTextLine4("price: " + myParameters.autoclickPrice +
" cookies. Owned: " + myParameters.autoclickOwned + ".");
                        scoreLabel.setText(score + " cookies");
                    }
                }           
        );

        





        


        



    }

}


ça donnerait ça,      mais ça marche toujours pas...

**Comment by nono35v** [comment]
![image](https://user-images.githubusercontent.com/35846302/37741946-cb23aeba-2d63-11e8-902d-9a7f22cea73e.png)
  

image pour voir si j'ai bien structuré mes fichiers..

**Comment by seinecle** [comment]
J'ai regardé le code de votre Form1 et je vois que:

- il manque certaines lignes "import", pour: Label, MultiButton, Component
-> voir [cette section](https://emlyon.github.io/codapps/generated-html/layout-design.html#_a_error_signal_when_creating_a_new_variable) de la leçon sur les imports.

- il faut déplacer vos variables `Label scoreLabel = new Label();` et `Label cookiesPerSecondLabel = new Label();` en tête de classe, comme expliqué [ici en Q&A](https://github.com/seinecle/codapps/issues/96).

Merci de vérifier ces deux points puis d'ouvrir une nouvelle issue sur Github pour les problèmes restants (ne poursuivez pas sur celle-ci, sauf pour évoquer les deux points ci-dessus. Merci!)

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
