### ISSUE TITLE
Problème de code dans le module 7

### ISSUE THREAD

**Issue by chloesarayed** [emlyon/codapps#5]
Bonjour, je n'arrive pas à visualiser le preview de l'application. Lorsque je clique sur "Run" la page Java s'ouvre puis se referme immédiatement avant que j'ai pu visualiser l'application.
Un message s'affiche alors dans "Output - *Nom de mon appli* (run)". Celui-ci dit :

"Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support
compile:
run:
java.lang.IllegalArgumentException: Component is already contained in Container: Container[x=0 y=6 width=320 height=474 name=null, layout = GridLayout, scrollableX = false, scrollableY = false, components = [Container, Container, Container]]
	at com.codename1.ui.Container.insertComponentAtImpl(Container.java:717)
	at com.codename1.ui.Container.insertComponentAt(Container.java:708)
	at com.codename1.ui.Container.addComponent(Container.java:637)
	at com.codename1.ui.Form.addComponent(Form.java:1323)
	at io.codapps.ChloeSarayeddineApp.Form1.<init>(Form1.java:77)
	at io.codapps.ChloeSarayeddineApp.MyApplication.start(MyApplication.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$1$1.run(Executor.java:123)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1116)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:911)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Java Result: 1
BUILD SUCCESSFUL (total time: 8 seconds)"

Que puis-je faire ?

**Comment by seinecle** [comment]
Il semble que votre code ajoute deux fois un certain Component (une Label? un Multibutton?) à votre Form.

Pouvez vous poster ici le code de votre Form1? On devrait voir la ligne fautive assez facilement (postez votre code sous forme de texte, pas comme une copie d'écran. Merci).

**Comment by chloesarayed** [comment]
Voila le code complet :

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.codapps.ChloeSarayeddineApp;

import com.codename1.components.MultiButton;
import com.codename1.components.ScaleImageButton;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.plaf.Style;


/**
 *
 * @author ChloeSarayeddine
 */
public class Form1 extends com.codename1.ui.Form {
 Resources theme = Resources.getGlobalResources();
 float score = 0f;
 Parameters myParameters = new Parameters();
      
 Image farmPic = theme.getImage("farm_50x37.png");
 Image clickPic = theme.getImage("click_50x64.png");
 Image cookieCentraPic = theme.getImage("cookie_200x200.png");
 Image grandmaPic = theme.getImage("grandma_50x50.png");
 Image cookiePressedPic = theme.getImage("cookie_200x200_star.png");
 
 long lastTimeScoreWasComputed; 

private void computeScore() { 
    long currentTimeInSeconds = System.currentTimeMillis() / 1000; 
    long lastTimeScoreWasComputedInSeconds = lastTimeScoreWasComputed / 1000;  

    if (currentTimeInSeconds != lastTimeScoreWasComputedInSeconds) {  
        score = score + myParameters.grandmaOwned * myParameters.grandmaProd + myParameters.farmOwned * myParameters.farmProd;  
        scoreLabel.setText(score + " cookies");  
        lastTimeScoreWasComputed = System.currentTimeMillis();  
    }
}

float cookiesPerSecond; 

private void computeCookiesPerSecond() {
    cookiesPerSecond =  myParameters.grandmaOwned * myParameters.grandmaProd + myParameters.farmOwned * myParameters.farmProd;
    cookiesPerSecondLabel.setText(cookiesPerSecond + " cookies per second"); 

}
long lastAnimatedTime; 

@Override
public boolean animate() {
    if (System.currentTimeMillis() / 100 > lastAnimatedTime / 100) { 
        computeScore(); 
        computeCookiesPerSecond(); 
        lastAnimatedTime = System.currentTimeMillis();
        return true;
    } else {
        return false;  
    }
}
 
  public Form1() {
      registerAnimated(this);
      
 //we put the form in a Grid layout : 3 rows, to divide the screen into three equal spaces.
 GridLayout gridLayoutThreeByOne = new GridLayout(3, 1); 
this.setLayout(gridLayoutThreeByOne); 

//we don't want the screen to be scrollable: everything should fit in it.
this.setScrollable(false);

//we create a Container that will contain everything in the "North" part of the BorderLayout:
Container northRegion = new Container();

//we choose a BorderLayout for this container:
BorderLayout borderLayoutNorth = new BorderLayout();
northRegion.setLayout(borderLayoutNorth);
      
//we create a Container that will contain everything in the "Center" part of the screen:
        Container centerRegion = new Container();

        //we choose a Grid Layout for this container:
        GridLayout gridLayoutFourByOne = new GridLayout(4, 1);
        centerRegion.setLayout(gridLayoutFourByOne);

        //we set this region to be scrollable, because there is too much content to fit
        centerRegion.setScrollableY(true);

        //we create a Container that will contain everything in the "South" part of the BorderLayout:
        Container southRegion = new Container();

        //we choose a Border Layout for this container:
        BorderLayout blSouth = new BorderLayout();
        southRegion.setLayout(blSouth);

        // we add the three containers to the Form, which is in a Gridlayout (three rows)

        // The northRegion will be in the top row because we add it first,
        // The centerRegion will be in the 2nd row because we add it in second
        // The southRegion will be in the 3rd row because we add it last.
        this.addComponent(northRegion);
        this.addComponent(centerRegion);
        this.addComponent(southRegion);
        
    // these lines of code should go inside  public Form1() { }
this.addComponent(northRegion);
this.addComponent(centerRegion);
this.addComponent(southRegion);

// creating the cookie central button
ScaleImageButton cookieCentral = new ScaleImageButton();
cookieCentral.setIcon(cookieCentraPic);
cookieCentral.setBackgroundType(Style.BACKGROUND_IMAGE_SCALED_FIT);
cookieCentral.getPressedStyle().setBgImage(cookiePressedPic);

// these lines of code should go inside  public Form1() { }
Label scoreLabel = new Label();
scoreLabel.setText("0 cookies");
scoreLabel.getStyle().setAlignment(Component.CENTER); //centering the text


// these lines of code should go inside  public Form1() { }
Label cookiesPerSecondLabel = new Label();
cookiesPerSecondLabel.setText("0 per second");
cookiesPerSecondLabel.getStyle().setAlignment(Component.CENTER); //centering the text
 
// these lines of code should go inside  public Form1() { }
northRegion.add(BorderLayout.NORTH, scoreLabel);
northRegion.add(BorderLayout.CENTER, cookieCentral);
northRegion.add(BorderLayout.SOUTH, cookiesPerSecondLabel);

// these lines of code should go inside  public Form1() { }
MultiButton autoclickButton = new MultiButton("Auto click");
autoclickButton.setIcon(clickPic);
autoclickButton.setTextLine2("\"Get your fingers some rest\"");
autoclickButton.setTextLine3("clicks 1 times every 10 seconds");
autoclickButton.setTextLine4("price: 15 cookies. Owned: 0");

// these lines of code should go inside  public Form1() { }
MultiButton grandmaButton = new MultiButton("Grandma");
grandmaButton.setIcon(grandmaPic);
grandmaButton.setTextLine2("\"Bake cookies with love\"");
grandmaButton.setTextLine3("each grandma produces 1 cookie per second");
grandmaButton.setTextLine4("price: 100 cookies. Owned: 0");

// these lines of code should go inside  public Form1() { }
//The farm
MultiButton farmButton = new MultiButton("Farm");
farmButton.setIcon(farmPic);
farmButton.setTextLine2("\"Harvest cookies every summer!\"");
farmButton.setTextLine3("each farm produces 3 cookies per second");
farmButton.setTextLine4("price: 500 cookies. Owned: 0");

// these lines of code should go inside  public Form1() { }
centerRegion.add(autoclickButton);
centerRegion.add(grandmaButton);
centerRegion.add(farmButton);

centerRegion.add(autoclickButton); 
centerRegion.add(grandmaButton); 
centerRegion.add(farmButton); 

cookieCentral.addActionListener(  
                (event) -> { 
                    score = score + 1;
                  scoreLabel.setText(score + " cookies");
                } 
        ); 
autoclickButton.addActionListener( 
        (event) -> {
            if (score >= myParameters.autoclickPrice) {
                myParameters.autoclickOwned = myParameters.autoclickOwned + 1;
                score = score - myParameters.autoclickPrice;
                myParameters.autoclickProd = myParameters.autoclickProd * myParameters.rateIncreaseProd;
                myParameters.autoclickPrice = myParameters.autoclickPrice * myParameters.rateIncreasePrice;
                autoclickButton.setTextLine4("price: " + myParameters.autoclickPrice + " cookies. Owned: " + myParameters.autoclickOwned + ".");
                scoreLabel.setText(score + " cookies");
            }
        }
); 

grandmaButton.addActionListener(
        (event) -> {
            if (score >= myParameters.grandmaPrice) {
                myParameters.grandmaOwned = myParameters.grandmaOwned + 1;
                score = score - myParameters.grandmaPrice;
                myParameters.grandmaProd = myParameters.grandmaProd * myParameters.rateIncreaseProd;
                myParameters.grandmaPrice = myParameters.grandmaPrice * myParameters.rateIncreasePrice;
                grandmaButton.setTextLine4("price: " + myParameters.grandmaPrice + " cookies. Owned: " + myParameters.grandmaOwned + ".");
                scoreLabel.setText(score + " cookies");
            }
        }
);

farmButton.addActionListener(
        (event) -> {
            if (score >= myParameters.farmPrice) {
                myParameters.farmOwned = myParameters.farmOwned + 1;
                score = score - myParameters.farmPrice;
                myParameters.farmProd = myParameters.farmProd * myParameters.rateIncreaseProd;
                myParameters.farmPrice = myParameters.farmPrice * myParameters.rateIncreasePrice;
                farmButton.setTextLine4("price: " + myParameters.farmPrice + " cookies. Owned: " + myParameters.farmOwned + ".");
                scoreLabel.setText(score + " cookies");
            }
        }
);

@Override
public boolean animate() {
    computeScore();
    computeCookiesPerSecond();
    return true;  
   }
}

**Comment by seinecle** [comment]
Bonsoir,
Les dernières lignes de votre code sont redondantes: 

```
@override
public boolean animate() {
computeScore();
computeCookiesPerSecond();
return true;
}
```

Car vous avez déjà écrit cette méthode plus haut. Supprimez cette méthode, en prenant garde à bien conserver l'accolade fermante `}` à la fin de votre fichier qui "clôt" votre classe.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
