### ISSUE TITLE
probleme téléchargement images module 6

### ISSUE THREAD

**Issue by AlexandreMANSOTTE** [emlyon/codapps#6]
bonjour,

peu à voir avec le code mais je n'arrive pas à télécharger les 4 images proposées pour créer l'app. Je suis sur mac.
Y'a t-il un autre moyen de les obtenir?

merci.

**Comment by seinecle** [comment]
Bonjour,
Merci de m'avoir averti. Je viens de mettre un fichier zip avec toutes les photos, téléchargeable, juste avant la liste des liens vers les photos. Vous le trouverez donc [ici](https://emlyon.github.io/codapps/generated-html/layout-design.html#_b_creating_variables_for_the_images_we_added_to_code_theme_res_code).
