### ISSUE TITLE
Problème Affichage Module 6, 1ère partie 

### ISSUE THREAD

**Issue by Chlodp** [emlyon/codapps#7]
Bonjour Monsieur, 
Lorsque je lance le Preview ( Module 6 à la fin de la 1ère partie ) le Simulator m'affiche l'App que j'avais du créer lors des précédentes séances.
Comment puis je faire pour que cela m'affiche l'écran blanc que je suis censée avoir ?

![screen shot 2018-03-23 at 3 33 36 pm](https://user-images.githubusercontent.com/36769063/37835168-d7e952d8-2eaf-11e8-823f-22b7c83ea3e0.png)

**Comment by seinecle** [comment]
Voir la réponse [ici](https://github.com/seinecle/codapps/issues/25).
