### ISSUE TITLE
problem with instantiating the Form when the app launches - module 6

### ISSUE THREAD

**Issue by AlexandreMANSOTTE** [emlyon/codapps#8]
bonjour,

je n'arrive pas à lancer l'app en preview comme cela devrait être le cas.. 
J'ai enlevé les lignes de codes à la fin de l'onglet MyApplication.java pour les remplacer par celles donner dans le module: 

public void start() {
      if(current != null){
          current.show();
return; }
Form1 mainScreen = new Form1();1
mainScreen.show();2 }

Mais un panneau rouge apparait à la fin.. cf. la photo
<img width="809" alt="capture d ecran 2018-03-23 a 17 55 31" src="https://user-images.githubusercontent.com/35762030/37843279-c35dad18-2ec4-11e8-94a3-5eb378bfbfea.png">

**Comment by seinecle** [comment]
Il vous manque une accolade fermante `}` je crois, en fin de fichier. Rajoutez-là  en ligne 63 et ce devrait fonctionner.

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
