### ISSUE TITLE
position des lignes de code module 6

### ISSUE THREAD

**Issue by Dorveaux** [emlyon/codapps#9]
Bonjour Monsieur, 
Je ne suis pas sûre d'avoir bien positionné mes lignes de code car à la fin je n'obtiens pas la même chose que ce qui est marqué sur le site: pouvez-vous me dire où est l'erreur ?
![2018-03-24](https://user-images.githubusercontent.com/36296420/37862666-08d68338-2f51-11e8-820f-a050a3008357.png)
![2018-03-24 1](https://user-images.githubusercontent.com/36296420/37862667-0bf2d7f6-2f51-11e8-9c47-d4a28757e1ce.png)
Merci d'avance
Alix Dorveaux

**Comment by seinecle** [comment]
Il y a une accolade fermante `}` en ligne 23 qui invalide tout ce qui suit. Supprimez-la.
